version: '3'
services:
  postgres:
    image: postgres
    container_name: "postgresdb"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      #- postgres-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #restart: unless-stopped
volumes:
  postgres-volume: